'use client';
import { useState } from 'react';
import { Appointment, usePlatform, statusLabel } from './Platform';
import { Modal } from './Shell';
import { dateKey, shiftDate, slots, isFutureSlot } from '@/lib/calendar';
export default function PortalCalendar({id}:{id:number}){
 const {t,state,date,settings,updateAppointment,money}=usePlatform();const [mode,setMode]=useState<'month'|'week'|'day'>('week');const [focus,setFocus]=useState(dateKey());const [selected,setSelected]=useState<Appointment|null>(null);const [newDay,setNewDay]=useState('');const [newTime,setNewTime]=useState('');const [error,setError]=useState('');
 const appointments=state.appointments.filter(a=>a.therapist===id&&a.status!=='cancelled');const weekday=new Date(`${focus}T12:00`).getDay();const start=mode==='month'?`${focus.slice(0,7)}-01`:mode==='week'?shiftDate(focus,-weekday):focus;const count=mode==='month'?new Date(Number(focus.slice(0,4)),Number(focus.slice(5,7)),0).getDate():mode==='week'?7:1;const days=Array.from({length:count},(_,i)=>shiftDate(start,i));const empty=mode==='month'?new Date(`${start}T12:00`).getDay():0;
 function move(dir:number){if(mode==='month'){const d=new Date(`${start}T12:00`);d.setMonth(d.getMonth()+dir);setFocus(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`);}else setFocus(shiftDate(focus,dir*(mode==='week'?7:1)));}
 function reschedule(){const conf=settings(id);if(!selected||!isFutureSlot(newDay,newTime)||!conf.days.includes(new Date(`${newDay}T12:00`).getDay())||!slots(conf.start,conf.end).includes(newTime)||state.appointments.some(a=>a.id!==selected.id&&a.therapist===id&&a.date===newDay&&a.time===newTime&&a.status!=='cancelled')){setError(t('Choose a future, available time within your working hours.','በሥራ ሰዓትዎ ውስጥ ያለ ያልተያዘ የወደፊት ሰዓት ይምረጡ።'));return;}updateAppointment(selected.id,{date:newDay,time:newTime,status:'confirmed'});setSelected(null);}
 function exportCSV(){const cell=(s:string)=>'"'+(/^[=+@-]/.test(s)?"'":'')+s.replaceAll('"','""')+'"';const rows=[[t('Client','ደንበኛ'),t('Date','ቀን'),t('Time UTC+3','ሰዓት UTC+3'),t('Status','ሁኔታ'),t('Price ETB','ዋጋ ብር')],...appointments.map(a=>[a.client==='demo-client'?t('Demo client','የማሳያ ደንበኛ'):a.client,a.date,a.time,statusLabel(a.status,t),String(a.price)])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='addis-demo-appointments.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section><div className="section-line"><h2>{t('Your calendar.','የቀጠሮ ሰሌዳዎ።')}</h2><button onClick={exportCSV}>{t('Export CSV','CSV አውርድ')}</button></div><div className="calendar-toolbar"><div className="segmented">{(['month','week','day'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='month'?t('Month','ወር'):m==='week'?t('Week','ሳምንት'):t('Day','ቀን')}</button>)}</div><div className="calendar-paging"><button onClick={()=>move(-1)}>{t('Previous','ቀዳሚ')}</button><button onClick={()=>setFocus(dateKey())}>{t('Today','ዛሬ')}</button><button onClick={()=>move(1)}>{t('Next','ቀጣይ')}</button></div></div><div className="section-line"><h3>{date(`${focus}T12:00`,{month:'long',year:'numeric',...(mode==='day'?{day:'numeric'}:{})})}</h3><small>{t('Addis Ababa time · UTC+3','የአዲስ አበባ ሰዓት · UTC+3')}</small></div><div className={`portal-calendar ${mode}`}>{mode==='month'&&Array.from({length:empty},(_,i)=><div key={`blank-${i}`} className="calendar-blank" aria-hidden="true"/>)}{days.map(d=><div key={d} className={`calendar-day ${d===dateKey()?'today':''}`}><button className="day-heading" onClick={()=>{setFocus(d);setMode('day');}}>{date(`${d}T12:00`,{weekday:'short',day:'numeric'})}</button>{appointments.filter(a=>a.date===d).sort((a,b)=>a.time.localeCompare(b.time)).map(a=><button className={`calendar-event ${a.status}`} key={a.id} onClick={()=>{setSelected(a);setNewDay(a.date);setNewTime(a.time);setError('');}}><strong>{a.time}</strong><span>{a.client==='demo-client'?t('Demo client','የማሳያ ደንበኛ'):a.client}</span><small>{statusLabel(a.status,t)}</small></button>)}{!appointments.some(a=>a.date===d)&&<small className="calendar-empty">{t('No bookings','ቀጠሮ የለም')}</small>}</div>)}</div>
 {selected&&<Modal title={t('Appointment details','የቀጠሮ ዝርዝር')} close={()=>setSelected(null)}><p>{selected.client==='demo-client'?t('Demo client','የማሳያ ደንበኛ'):selected.client} · {statusLabel(selected.status,t)}</p><p>{date(`${selected.date}T12:00`)} · {selected.time} · {money(selected.price)}</p><div className="form-actions">{selected.status==='pending'&&<button className="solid" onClick={()=>{updateAppointment(selected.id,{status:'confirmed'});setSelected(null);}}>{t('Confirm','አረጋግጥ')}</button>}{selected.status==='confirmed'&&<button onClick={()=>{updateAppointment(selected.id,{status:'completed'});setSelected(null);}}>{t('Mark completed','ተጠናቋል ብለው ያመልክቱ')}</button>}{selected.status!=='completed'&&<button onClick={()=>{updateAppointment(selected.id,{status:'cancelled'});setSelected(null);}}>{t('Cancel appointment','ቀጠሮ ሰርዝ')}</button>}</div>{selected.status!=='completed'&&<><h3>{t('Reschedule','እንደገና ቀጠሮ ያዙ')}</h3><p>{t('Changes update this local demo booking. No notification is sent.','ለውጦች ይህን የማሳያ ቀጠሮ ያዘምናሉ። ማሳወቂያ አይላክም።')}</p><div className="field-grid"><label>{t('Date','ቀን')}<input type="date" min={dateKey()} value={newDay} onChange={e=>setNewDay(e.target.value)}/></label><label>{t('Time','ሰዓት')}<select value={newTime} onChange={e=>setNewTime(e.target.value)}>{slots(settings(id).start,settings(id).end).map(s=><option key={s}>{s}</option>)}</select></label></div>{error&&<p role="alert">{error}</p>}<button className="solid" onClick={reschedule}>{t('Save new time','አዲስ ሰዓት አስቀምጥ')}</button></>}</Modal>}
 </section>;
}
