'use client';
import { useState } from 'react';
import Link from 'next/link';
import { usePlatform, statusLabel } from '@/components/Platform';
import { Page, DemoNote, Presence, Modal } from '@/components/Shell';
import PortalCalendar from '@/components/PortalCalendar';
import PortalSettings from '@/components/PortalSettings';
import { dateKey } from '@/lib/calendar';
export default function Portal(){const {t,people,state,messages,reply,money,date,clear}=usePlatform();const [id,setId]=useState(1);const [tab,setTab]=useState('overview');const [draft,setDraft]=useState('');const [reset,setReset]=useState(false);const person=people.find(p=>p.id===id)!;const appointments=state.appointments.filter(a=>a.therapist===id);const receipts=state.receipts.filter(r=>r.therapist===id);const thread=messages.filter(m=>m.therapist===id);const tabs=[['overview',t('Overview','አጠቃላይ')],['calendar',t('Calendar','የቀጠሮ ሰሌዳ')],['inbox',t('Inbox','መልዕክቶች')],['rates',t('Rates & availability','ዋጋና የሥራ ጊዜ')],['profile',t('Profile & photo','መገለጫና ፎቶ')]];
return <Page wide><DemoNote/><div className="portal-intro"><div><span className="eyebrow">{t('THERAPIST WORKSPACE','የባለሙያ የሥራ ቦታ')}</span><h1>{t('Care, organized.','የተደራጀ እንክብካቤ።')}</h1><Presence id={id}/></div><label>{t('Preview a demo therapist','የማሳያ ባለሙያ ይምረጡ')}<select value={id} onChange={e=>{setId(Number(e.target.value));setDraft('');}}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><p className="notice">{t('This is an open demonstration workspace, not a protected professional account. All changes are local to this browser.','ይህ ክፍት የማሳያ የሥራ ቦታ ነው፤ የተጠበቀ የሙያ መለያ አይደለም። ለውጦች በዚህ አሳሽ ብቻ ይቀመጣሉ።')} <Link href="/register">{state.registration?t('Review demo application','የማሳያ ማመልከቻ ይገምግሙ'):t('Register as a therapist','እንደ ባለሙያ ይመዝገቡ')}</Link></p><nav className="portal-tabs" aria-label={t('Portal sections','የፖርታል ክፍሎች')}>{tabs.map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
{tab==='overview'&&<><div className="metric-grid">{[[t('Today’s appointments','የዛሬ ቀጠሮዎች'),appointments.filter(a=>a.date===dateKey()&&a.status!=='cancelled').length],[t('Pending requests','በመጠባበቅ ላይ ያሉ ጥያቄዎች'),appointments.filter(a=>a.status==='pending').length],[t('Demo package sales','የማሳያ ጥቅል ሽያጮች'),money(receipts.reduce((n,r)=>n+r.amount,0))],[t('Messages in this visit','በዚህ ጉብኝት ያሉ መልዕክቶች'),thread.length]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="section-line"><h2>{t('Upcoming appointments','መጪ ቀጠሮዎች')}</h2><button onClick={()=>setTab('calendar')}>{t('Open calendar','የቀጠሮ ሰሌዳ ክፈት')}</button></div>{!appointments.some(a=>a.date>=dateKey()&&a.status!=='cancelled')?<div className="empty-state"><p>{t('Your calendar is clear. Create a sample booking from the client flow to see it here.','የቀጠሮ ሰሌዳዎ ባዶ ነው። እዚህ ለማየት ከደንበኛው ገጽ የሙከራ ቀጠሮ ይያዙ።')}</p><Link href={`/schedule/${id}`}>{t('Try the booking flow','የቀጠሮ ሂደቱን ይሞክሩ')}</Link></div>:appointments.filter(a=>a.date>=dateKey()&&a.status!=='cancelled').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(a=><div className="receipt-row" key={a.id}><span>{a.client==='demo-client'?t('Demo client','የማሳያ ደንበኛ'):a.client}<small>{date(`${a.date}T12:00`)} · {a.time}</small></span><span>{statusLabel(a.status,t)}</span><strong>{money(a.price)}</strong></div>)}<h2>{t('Package payment history','የጥቅል ክፍያ ታሪክ')}</h2><p>{t('Simulated sales only. No real money, payouts, or invoices are processed.','የማሳያ ሽያጮች ብቻ። እውነተኛ ገንዘብ፣ ክፍያ ወይም ደረሰኝ አይፈጸምም።')}</p>{!receipts.length?<p>{t('No demo purchases yet.','እስካሁን የማሳያ ግዢ የለም።')}</p>:receipts.map(r=><div className="receipt-row" key={r.id}><span>{date(r.at)}<small>{t('Demo receipt','የማሳያ ደረሰኝ')} {r.id.slice(0,8)}</small></span><strong>{money(r.amount)}</strong></div>)}</>}
{tab==='calendar'&&<PortalCalendar key={id} id={id}/>}{tab==='rates'&&<PortalSettings key={`rates-${id}`} id={id}/>}{tab==='profile'&&<PortalSettings key={`profile-${id}`} id={id} profile/>}
{tab==='inbox'&&<section className="portal-inbox"><h2>{t('Client conversation','የደንበኛ ውይይት')}</h2><p>{t('This demo has one local client conversation per therapist. Replies appear in the client chat during this visit; nothing is sent externally.','በዚህ ማሳያ ለእያንዳንዱ ባለሙያ አንድ የደንበኛ ውይይት አለ። መልሶች በዚህ ጉብኝት በደንበኛው ውይይት ውስጥ ይታያሉ፤ ወደ ውጭ አይላኩም።')}</p><div className="portal-message-list">{!thread.length?<p>{t('No messages yet.','እስካሁን መልዕክት የለም።')}</p>:thread.map(m=><article className={`message ${m.from}`} key={m.id}><small>{m.from==='client'?t('Demo client','የማሳያ ደንበኛ'):person.name}</small>{m.text&&<p>{m.text}</p>}{m.audio&&<audio controls src={m.audio} aria-label={t('Voice message','የድምፅ መልዕክት')}/>}</article>)}</div><form onSubmit={e=>{e.preventDefault();reply(id,draft);setDraft('');}}><label>{t('Reply as therapist','እንደ ባለሙያ መልስ ይጻፉ')}<textarea value={draft} maxLength={2000} onChange={e=>setDraft(e.target.value)} rows={3}/></label><button className="solid" disabled={!draft.trim()||!thread.some(m=>m.from==='client')}>{t('Send demo reply','የማሳያ መልስ ላክ')}</button><Link href={`/chat?therapist=${id}`}>{t('View client chat','የደንበኛውን ውይይት ይመልከቱ')}</Link></form></section>}
<div className="portal-footer"><small>{t('Demo data is stored in this browser. Messages and audio are kept only during this visit.','የማሳያ መረጃ በዚህ አሳሽ ይቀመጣል። መልዕክቶችና ድምፆች በዚህ ጉብኝት ብቻ ይቆያሉ።')}</small><button onClick={()=>setReset(true)}>{t('Reset demo data','የማሳያ መረጃ አጥፋ')}</button></div>{reset&&<Modal title={t('Reset this browser’s demo?','የዚህን አሳሽ ማሳያ ዳግም ያስጀምሩ?')} close={()=>setReset(false)}><p>{t('This removes saved demo bookings, package credits, receipts, application details, photos, and messages from this browser.','ይህ የተቀመጡ የማሳያ ቀጠሮዎችን፣ ክሬዲቶችን፣ ደረሰኞችን፣ ማመልከቻዎችን፣ ፎቶዎችንና መልዕክቶችን ከዚህ አሳሽ ያስወግዳል።')}</p><button className="solid" onClick={()=>{clear();setReset(false);setTab('overview');}}>{t('Reset demo','ማሳያውን ዳግም ጀምር')}</button></Modal>}</Page>;
}
