'use client';
import { Suspense, useState } from 'react';
import { useParams, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { usePlatform } from '@/components/Platform';
import { Page, DemoNote } from '@/components/Shell';
import { isFutureSlot, slots } from '@/lib/calendar';
import { discountedPrice } from '@/lib/commerce';
function Review(){
 const params=useParams();const q=useSearchParams();const {t,people,settings,book,date,money}=usePlatform();const id=Number(params.id);const p=people.find(p=>p.id===id);const day=q.get('date')||'';const time=q.get('time')||'';const medium=q.get('type')==='inperson'?'inperson':'online';const conf=settings(id);const [name,setName]=useState('');const [done,setDone]=useState(false);const [error,setError]=useState('');const price=discountedPrice(medium==='online'?conf.online:conf.inperson,conf.discount);
 const valid=p&&/^\d{4}-\d{2}-\d{2}$/.test(day)&&slots(conf.start,conf.end).includes(time)&&isFutureSlot(day,time)&&conf.days.includes(new Date(`${day}T12:00`).getDay());
 if(!valid)return <Page><h1>{t('Choose an appointment first.','መጀመሪያ ቀጠሮ ይምረጡ።')}</h1><Link href={p?`/schedule/${id}`:'/therapists'}>{t('Choose a time','ሰዓት ይምረጡ')}</Link></Page>;
 return <Page><DemoNote/><span className="eyebrow">{t('03 / REVIEW YOUR APPOINTMENT','03 / ቀጠሮዎን ይገምግሙ')}</span><h1>{done?t('Request saved.','ጥያቄው ተቀምጧል።'):t('Your next step.','ቀጣዩ እርምጃዎ።')}</h1>{done?<div className="notice"><p>{t('Your demo request is in My bookings and the therapist portal. No real appointment has been arranged and no payment was taken.','የማሳያ ጥያቄዎ በቀጠሮዎቼና በባለሙያ ፖርታል ውስጥ ይታያል። እውነተኛ ቀጠሮ አልተያዘም፣ ክፍያም አልተወሰደም።')}</p><Link className="solid" href="/appointments">{t('View my bookings','ቀጠሮዎቼን አሳይ')}</Link></div>:<form onSubmit={e=>{e.preventDefault();if(book({therapist:id,date:day,time,medium,price,client:name.trim()||'demo-client'}))setDone(true);else setError(t('This time was just booked. Please choose another time.','ይህ ሰዓት አሁን ተይዟል። ሌላ ሰዓት ይምረጡ።'));}}><dl className="summary-list"><div><dt>{t('Therapist','ባለሙያ')}</dt><dd>{p.name}</dd></div><div><dt>{t('Date & time','ቀንና ሰዓት')}</dt><dd>{date(`${day}T12:00`)} · {time} (UTC+3)</dd></div><div><dt>{t('Session','ቀጠሮ')}</dt><dd>{medium==='online'?t('Video · 60 minutes','ቪዲዮ · 60 ደቂቃ'):t('In person · 60 minutes','በአካል · 60 ደቂቃ')}</dd></div><div><dt>{t('Session price','የቀጠሮ ዋጋ')}</dt><dd>{money(price)}</dd></div></dl><label>{t('Demo client name (optional)','የማሳያ ደንበኛ ስም (አማራጭ)')}<input value={name} maxLength={60} onChange={e=>setName(e.target.value)} placeholder={t('Use a sample name','የሙከራ ስም ይጠቀሙ')}/></label><p className="notice">{t('Session bookings and message packages are separate. This demo request does not charge you or add message credits.','የቀጠሮ ምዝገባና የመልዕክት ጥቅል የተለያዩ ናቸው። ይህ የማሳያ ጥያቄ ክፍያ አያስከፍልም፣ የመልዕክት ክሬዲትም አይጨምርም።')}</p>{error&&<p role="alert">{error}</p>}<div className="form-actions"><Link href={`/schedule/${id}`}>{t('Change time','ሰዓት ቀይር')}</Link><button className="solid" type="submit">{t('Save demo request','የማሳያ ጥያቄ አስቀምጥ')}</button></div></form>}</Page>;
}
export default function PaymentPage(){return <Suspense><Review/></Suspense>;}
